background {
  monitor = # monitor-agnostic
  path = ~/Pictures/Discworld.jpeg
  blur_passes = 1
  blur_size = 7
}
input-field {
  monitor =
  size = 20%, 5%
  font_family = Noto Sans
  dots_size = 0.08
  position = 0, -150
}
label {
  monitor =
  text = $TIME
  font_size = 100
  position = 0, 0
}
general {
  ignore_empty_input = true
}
